import { Inter } from "next/font/google";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "../components/StoryblokProvider";

const inter = Inter({ subsets: ["latin"] });

storyblokInit({
  apiOptions: {
    region: "us",
  },
  accessToken: "{{YOUR_TOKEN}}",
  use: [apiPlugin],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
         <html lang="en">
             <body>{children}</body>
        </html>
    </StoryblokProvider>
  )
}